/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionrestaurantesFinal;

import Clases.GestionRestaurantes;
import Clases.Restaurante;
import java.awt.Color;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jucaso
 */
public class AdmonCC extends javax.swing.JFrame {

    static Vector restaurantes;
            
    public AdmonCC() {
        initComponents();
        ImageIcon cerrar = new ImageIcon("cerrar.png");       
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        conectar();
        setRestBox();
    }
    public void conectar(){
        restaurantes = new Vector();
        restArea.setText("");
        try {
             GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
             GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT * FROM restaurante order by nrolocal;");          
             //GestionRestaurantes.s.close();
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }        
        
        try {
            while(GestionRestaurantes.rs.next()){               
                    Restaurante rest;
                    rest = new Restaurante( GestionRestaurantes.rs.getString(2), GestionRestaurantes.rs.getInt(1));
                    restaurantes.add(rest);                              
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar bro... " + e);
        }
    }
    
    public void setRestBox(){
        for (int i = 0; i < restaurantes.size(); i++) {
             int nroLocal = ((Restaurante)restaurantes.elementAt(i)).verResId();
             restBox.addItem(Integer.toString(nroLocal));
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        restArea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        restBox = new javax.swing.JComboBox<>();
        eliminarB = new javax.swing.JButton();
        SalirB = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 210, 230, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 580, 10));

        restArea.setEditable(false);
        restArea.setBackground(new java.awt.Color(204, 204, 204));
        restArea.setColumns(20);
        restArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        restArea.setRows(5);
        jScrollPane1.setViewportView(restArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 294));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        jButton3.setText("Ver restaurantes");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 129, 32));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        jButton2.setText("Generar reportes");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 160, 170, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        jButton1.setText("Registrar restaurante");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 110, 170, 40));

        restBox.setBackground(new java.awt.Color(204, 204, 204));
        restBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        restBox.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(restBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 270, 80, -1));

        eliminarB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eliminarB.setForeground(new java.awt.Color(255, 255, 255));
        eliminarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        eliminarB.setText("Eliminar");
        eliminarB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        eliminarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        eliminarB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        eliminarB.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        eliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 69, 23));

        SalirB.setBackground(new java.awt.Color(153, 153, 153));
        SalirB.setForeground(new java.awt.Color(153, 153, 153));
        SalirB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/cerrar.png"))); // NOI18N
        SalirB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        SalirB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirB.setFocusable(false);
        SalirB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirBMouseExited(evt);
            }
        });
        SalirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBActionPerformed(evt);
            }
        });
        getContentPane().add(SalirB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 30, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/AdmonC.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 604, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        restArea.setText("");
        
        for(int i=0;i<restaurantes.size();i++){
            restArea.setText(restArea.getText()+
            "\nNúmero de local:: " + ((Restaurante)restaurantes.elementAt(i)).verResId()+
            "\nNombre: " + ((Restaurante)restaurantes.elementAt(i)).verResNombre() +
            "\n______________________________\n");
        }
        restBox.removeAllItems();
            setRestBox();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void eliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBActionPerformed
        int confirmaElimina = 1;
        confirmaElimina = JOptionPane.showConfirmDialog(null, "¿ELIMINAR RESTAURANTE?", "CONFIRMACION DE ELIMINACIÓN", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
        if(confirmaElimina == 0){
            // Elimina cliente
            int idRestAux = Integer.parseInt(restBox.getSelectedItem()+"");
            String auxElimina = "DELETE"
            + " FROM cliente"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina empleado
            auxElimina = "DELETE"
            + " FROM empleado"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina insumos
            auxElimina = "DELETE"
            + " FROM insumos"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina pedido
            auxElimina = "DELETE"
            + " FROM pedido"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina pedidodetalle
            auxElimina = "DELETE"
            + " FROM pedidodetalle"
            + " WHERE nrolocal = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina pedidotiene
            auxElimina = "DELETE"
            + " FROM pedidotiene"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina producto
            auxElimina = "DELETE"
            + " FROM producto"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina requiere
            auxElimina = "DELETE"
            + " FROM requiere"
            + " WHERE idrest = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }
            // Elimina restaurante
            auxElimina = "DELETE"
            + " FROM restaurante"
            + " WHERE nrolocal = " + idRestAux + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxElimina);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            }

            JOptionPane.showMessageDialog(null, "RESTAURANTE ELIMINADO CON ÉXITO", "AVISO",JOptionPane.PLAIN_MESSAGE, login.CheckIcon);
            restBox.removeAllItems();
            restArea.setText("");
            restaurantes.removeAllElements();
            conectar();
            setRestBox();
        }
    }//GEN-LAST:event_eliminarBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        regRestaurante rr = new regRestaurante();
        rr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Reportes r = new Reportes();
        r.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SalirBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirBMouseEntered
        // TODO add your handling code here:
        SalirB.setBackground(new Color (204,204,204));
    }//GEN-LAST:event_SalirBMouseEntered

    private void SalirBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirBMouseExited
        // TODO add your handling code here:
        SalirB.setBackground(new Color (153,153,153));
    }//GEN-LAST:event_SalirBMouseExited

    private void SalirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login log;
        try {
            log = new login();
            log.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(gestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalirBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmonCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmonCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmonCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmonCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmonCC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirB;
    private javax.swing.JButton eliminarB;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea restArea;
    private javax.swing.JComboBox<String> restBox;
    // End of variables declaration//GEN-END:variables
}
