/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionrestaurantesFinal;

import java.util.Vector;
import javax.swing.JOptionPane;
import Clases.*;

/**
 *
 * @author Jucaso
 */
public class añadirInsEx extends javax.swing.JFrame {

    Vector insumos = new Vector();
    public añadirInsEx() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setVectorInsumos();
        setInsumosBox();
    }
    
    public void setVectorInsumos(){
        try {
             GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
             GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT * FROM insumos order by id;");          
             //GestionRestaurantes.s.close();
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }        
        
        try {
            while(GestionRestaurantes.rs.next()){
                if(GestionRestaurantes.rs.getInt(5) == login.auxIdRes){
                    Insumos ins;
                    ins = new Insumos(GestionRestaurantes.rs.getInt(1), GestionRestaurantes.rs.getString(2),
                    GestionRestaurantes.rs.getString(3), GestionRestaurantes.rs.getInt(4));
                    insumos.add(ins);
                }
                    
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar bro... " + e);
        }
    }
    
    public void setInsumosBox(){
        for (int i = 0; i < insumos.size(); i++) {
            insumosBox.addItem(((Insumos)insumos.elementAt(i)).verInsNombre());
        }
    }
    
    public int obtenerCodigoInsumo(int index){
        int codigoIns = ((Insumos)insumos.elementAt(index)).verInsId();
        return codigoIns;       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        insumosBox = new javax.swing.JComboBox<>();
        cantidadField = new javax.swing.JTextField();
        agregarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 285, 10));

        insumosBox.setBackground(new java.awt.Color(102, 102, 102));
        insumosBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insumosBox.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(insumosBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 109, -1));

        cantidadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cantidadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        agregarB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        agregarB.setForeground(new java.awt.Color(255, 255, 255));
        agregarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        agregarB.setText("Agregar");
        agregarB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        agregarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        agregarB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        agregarB.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        agregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBActionPerformed(evt);
            }
        });
        getContentPane().add(agregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 79, 30));

        cancelarB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelarB.setForeground(new java.awt.Color(255, 255, 255));
        cancelarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        cancelarB.setText("Volver");
        cancelarB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        cancelarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        cancelarB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        cancelarB.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 81, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/AñadirIE.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 174));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadFieldActionPerformed

    private void agregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBActionPerformed
        if(!cantidadField.getText().isEmpty() && CrearUsuario.isNumeric(cantidadField.getText())){
            String auxUpdate = "UPDATE insumos"
                + " SET cantidadunidad = cantidadunidad + " + Integer.parseInt(cantidadField.getText())
                + " WHERE id = " + obtenerCodigoInsumo(insumosBox.getSelectedIndex()) + ";";
            try {
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.s.executeUpdate(auxUpdate); 
                cantidadField.setText("");
                insumosBox.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, "INSUMO ACTUALIZADO CON EXITO", "INFORMACIÓN", JOptionPane.PLAIN_MESSAGE, login.CheckIcon);
            } catch (Exception e) {
                System.out.println("Error bro.. " + e);
            } 
            
        }
        else{
            JOptionPane.showMessageDialog(null, "CANTIDAD NO VÁLIDA", "ERROR", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
        }
        
    }//GEN-LAST:event_agregarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        this.dispose();
        AdmonRes a1 = new AdmonRes();
        a1.setVisible(true);
    }//GEN-LAST:event_cancelarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadirInsEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadirInsEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadirInsEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadirInsEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new añadirInsEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarB;
    private javax.swing.JButton cancelarB;
    private javax.swing.JTextField cantidadField;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox<String> insumosBox;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
