/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionrestaurantesFinal;

import Clases.GestionRestaurantes;
import Clases.Restaurante;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Jucaso
 */
public class CrearUsuario extends javax.swing.JFrame {
    
    int index = 0;
    static Vector restVec;
    Vector usuarios = new Vector();
    
    public CrearUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setRestaurantesComboBox();
        setUsuariosVector();
        
             UIManager.put("OptionPane.background",new ColorUIResource(51,51,51));
             UIManager.put("Panel.background",new ColorUIResource(51,51,51));
             UIManager.put("OptionPane.messageForeground",Color.WHITE);
             UIManager.put("Button.background",Color.BLACK);
             UIManager.put("Button.foreground",Color.WHITE);
        
    }
    public void setUsuariosVector(){
        try {
             GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
             GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT id FROM empleado;");
             //GestionRestaurantes.s.close();
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }

        try {
            while(GestionRestaurantes.rs.next()){
                usuarios.add(GestionRestaurantes.rs.getInt(1));
            }
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }
    }
    public int verificaUsuario(int codigo){
        int aux = 0;
        for (int i = 0; i < usuarios.size(); i++) {
            if((int)usuarios.elementAt(i) == codigo){
                aux = 1;
                break;
            }
        }
        if(aux == 1){
            //Usuario existe
            return 1;
        }
        else{
            //Usuario no existe
            return 0;
        }
    }
    
    public static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    public static boolean isNumericLong(String cadena){
	try {
		Long.parseLong(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    public void setRestaurantesComboBox(){
        restVec = new Vector();
        try {
             GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
             GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT * FROM restaurante;");          
             //GestionRestaurantes.s.close();
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }
        
        try {
            while(GestionRestaurantes.rs.next()){
                Restaurante res;
                res = new Restaurante(GestionRestaurantes.rs.getString(2), GestionRestaurantes.rs.getInt(1));
                restVec.add(res);
            } 
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        } 
        for (int i = 0; i < restVec.size(); i++) {
            restauranteBox.addItem(Integer.toString(((Restaurante)restVec.elementAt(i)).verResId()));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        direccionField = new javax.swing.JTextField();
        celularField = new javax.swing.JTextField();
        añoBox = new javax.swing.JComboBox<>();
        mesBox = new javax.swing.JComboBox<>();
        diaBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        apellidoField = new javax.swing.JTextField();
        usuarioField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        tipoUserBox = new javax.swing.JComboBox<>();
        cancelarBoton = new javax.swing.JButton();
        guardarBoton = new javax.swing.JButton();
        tipoIdBox = new javax.swing.JComboBox<>();
        restauranteBox = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 410));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 129, -1));
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 204, 129, -1));
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 127, 129, -1));
        getContentPane().add(direccionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 169, 210, -1));
        getContentPane().add(celularField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 129, -1));

        añoBox.setBackground(new java.awt.Color(102, 102, 102));
        añoBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        añoBox.setForeground(new java.awt.Color(255, 255, 255));
        añoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", " " }));
        añoBox.setName(""); // NOI18N
        añoBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                añoBisisesto(evt);
            }
        });
        añoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoBoxActionPerformed(evt);
            }
        });
        getContentPane().add(añoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 204, -1, -1));

        mesBox.setBackground(new java.awt.Color(102, 102, 102));
        mesBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mesBox.setForeground(new java.awt.Color(255, 255, 255));
        mesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        mesBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bisiesto(evt);
            }
        });
        mesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 204, -1, -1));

        diaBox.setBackground(new java.awt.Color(102, 102, 102));
        diaBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        diaBox.setForeground(new java.awt.Color(255, 255, 255));
        diaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(diaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 204, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("/");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 204, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("/");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 204, 10, 20));
        getContentPane().add(apellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 90, 210, -1));
        getContentPane().add(usuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 245, 129, -1));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 244, 210, -1));

        tipoUserBox.setBackground(new java.awt.Color(102, 102, 102));
        tipoUserBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipoUserBox.setForeground(new java.awt.Color(255, 255, 255));
        tipoUserBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operario", "Admon restaurante", "Admon centro comercial" }));
        getContentPane().add(tipoUserBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 286, 150, -1));

        cancelarBoton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelarBoton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        cancelarBoton.setText("VOLVER");
        cancelarBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        cancelarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarBoton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        cancelarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        cancelarBoton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 363, 89, 30));

        guardarBoton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardarBoton.setForeground(new java.awt.Color(255, 255, 255));
        guardarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        guardarBoton.setText("GUARDAR");
        guardarBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        guardarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarBoton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        guardarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        guardarBoton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(guardarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 363, 89, 30));

        tipoIdBox.setBackground(new java.awt.Color(102, 102, 102));
        tipoIdBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tipoIdBox.setForeground(new java.awt.Color(255, 255, 255));
        tipoIdBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Cedula de extranjeria", "Pasaporte", "Tarjeta de identidad" }));
        tipoIdBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        tipoIdBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoIdBox.setFocusable(false);
        tipoIdBox.setOpaque(false);
        getContentPane().add(tipoIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 127, 210, -1));

        restauranteBox.setBackground(new java.awt.Color(102, 102, 102));
        restauranteBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        restauranteBox.setForeground(new java.awt.Color(255, 255, 255));
        restauranteBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                restaurante(evt);
            }
        });
        restauranteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restauranteBoxActionPerformed(evt);
            }
        });
        getContentPane().add(restauranteBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 284, 52, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/CrearU.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 550, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesBoxActionPerformed

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
    int auxAñade = 1;
        if(!nombreField.getText().isEmpty() && !isNumeric(nombreField.getText())){
            String nombre= "'"+nombreField.getText()+"'";
            
            if(!apellidoField.getText().isEmpty() && !isNumeric(apellidoField.getText())){
                    String apellido = "'"+apellidoField.getText()+"'";
                    
                if(!idField.getText().isEmpty() && isNumeric(idField.getText())){
                    if(verificaUsuario(Integer.parseInt(idField.getText())) == 0){
                        int id = Integer.parseInt(idField.getText());                             
                    
                    if(isNumericLong(celularField.getText()) ){
                        long celular = Long.parseLong(celularField.getText());
                        
                        if(!direccionField.getText().isEmpty()){
                            String direccion = "'"+direccionField.getText()+"'";
                            
                            if(emailField.getText().contains("@")){
                                    String email = "'"+emailField.getText()+"'"; 
                                    
                                if(!usuarioField.getText().isEmpty()){
                                    String usuario = "'"+usuarioField.getText()+"'";
                                                                                                                          
                                    if(!passField.getText().isEmpty()){
                                        String contraseña = "'"+passField.getText()+"'";                                                                              
                                        int año = Integer.parseInt(añoBox.getSelectedItem()+""), mes = Integer.parseInt(mesBox.getSelectedItem()+""), dia = Integer.parseInt(diaBox.getSelectedItem()+"");
                                        String fechaIngreso = "'"+ año + "-" + mes + "-" + "-" + dia +"'";
                                        String tipoID = "'"+tipoIdBox.getSelectedItem()+"'"; 
                                        int restaurante = 0;
                                        if(tipoUserBox.getSelectedItem().equals("Admon centro comercial")){
                                            restaurante = 0;
                                        }
                                        else{
                                            restaurante = Integer.parseInt(restauranteBox.getSelectedItem()+"");
                                        }
                                        String tipoUsuario = "'"+tipoUserBox.getSelectedItem()+"'";
                                        
                                        auxAñade = JOptionPane.showConfirmDialog(null, "¿CREAR USUARIO?", "CONFIRMACION DE CREACIÓN", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
                                        
                                        if(auxAñade == 0){                                           
                                                String auxUpdate = "insert into empleado values (" + id + "," + tipoID  + "," + nombre + 
                                                 "," + apellido + "," + email  + "," + direccion + "," + celular + "," + fechaIngreso + 
                                                 "," + usuario + "," + contraseña + "," + tipoUsuario + "," + restaurante +
                                                 "," +  0 + "," + "'Activo'" + ");";
                                                try {
                                                     GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                                                     GestionRestaurantes.s.executeUpdate(auxUpdate);  
                                                     JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO","AVISO",JOptionPane.PLAIN_MESSAGE, login.CheckIcon);
                                                     //GestionRestaurantes.s.close();
                                                } catch (Exception e) {
                                                    System.out.println("Error bro... " + e);
                                                }
                                                
                                                 Calendar fechaHoy = Calendar.getInstance();  
                                                 int añoHoy, mesHoy, diaHoy;
                                                 añoHoy = fechaHoy.get(fechaHoy.YEAR);
                                                 mesHoy = fechaHoy.get(fechaHoy.MONTH) + 1;
                                                 diaHoy = fechaHoy.get(fechaHoy.DAY_OF_MONTH);
                                                 String fechaCreacion = "'" + añoHoy + "-" + mesHoy + "-" + diaHoy + "'";
                                                 
                                                 auxUpdate = "insert into usuarioingreso values(" + id + "," + fechaCreacion + ");";
                                                 try {
                                                    GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                                                    GestionRestaurantes.s.executeUpdate(auxUpdate);
                                                } catch (Exception e) {
                                                     System.out.println("Error bro... " + e);
                                                }
                                                 nombreField.setText("");
                                                 apellidoField.setText("");
                                                 idField.setText("");
                                                 celularField.setText("");
                                                 direccionField.setText("");
                                                 emailField.setText("");
                                                 usuarioField.setText("");
                                                 passField.setText("");                                               
                                        }                                       
                                    } 
                                    else{
                                        JOptionPane.showMessageDialog(null, "CONTRASEÑA NO VÁLIDA", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon); 
                                        passField.setText("");
                                        }
                                } 
                                else{
                                    JOptionPane.showMessageDialog(null, "USUARIO NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon); 
                                    usuarioField.setText("");
                                    }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "EMAIL NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon); 
                                emailField.setText("");
                                }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "DIRECCIÓN NO VÁLIDA", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon); 
                            direccionField.setText("");
                            }                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "CELULAR NO VÁLIDO", "ADVERTENCIA",JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                        celularField.setText("");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "ID EXISTENTE - NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                        idField.setText("");
                        
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "ID NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon); 
                    idField.setText("");
                    }
            } 
            else{
                JOptionPane.showMessageDialog(null, "APELLIDO NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                apellidoField.setText("");
                }
        } 
        else{
            JOptionPane.showMessageDialog(null, "NOMBRE NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
            nombreField.setText("");
        }
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
       gestionUsuarios g1 = new gestionUsuarios();
        g1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void restauranteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restauranteBoxActionPerformed
        
    }//GEN-LAST:event_restauranteBoxActionPerformed

    private void restaurante(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_restaurante
                     
    }//GEN-LAST:event_restaurante

    private void añoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoBoxActionPerformed

    private void añoBisisesto(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_añoBisisesto
        mesBox.setSelectedIndex(0);
        diaBox.setSelectedIndex(0);
    }//GEN-LAST:event_añoBisisesto

    private void bisiesto(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bisiesto
        int año = Integer.parseInt(añoBox.getSelectedItem()+"");
        int mes = Integer.parseInt(mesBox.getSelectedItem()+"");

        diaBox.removeAllItems();
        if(((año % 4 == 0 && año % 100 != 0) || (año % 400 == 0)) &&  mes == 02){
            for (int i = 0; i < 29; i++) {               
                diaBox.addItem(Integer.toString(i+1));
            }
        }
        else if(mes == 02){
            for (int i = 0; i < 28; i++) {               
                diaBox.addItem(Integer.toString(i+1));
            }
        }
        else if(mes == 4 || mes == 6 || mes == 9 || mes == 11){
            for (int i = 0; i < 30; i++) {               
                diaBox.addItem(Integer.toString(i+1));
            }
        }
        else{
            for (int i = 0; i < 31; i++) {               
                diaBox.addItem(Integer.toString(i+1));
            }
        }
    }//GEN-LAST:event_bisiesto
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField apellidoField;
    private javax.swing.JComboBox<String> añoBox;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JTextField celularField;
    private javax.swing.JComboBox<String> diaBox;
    private javax.swing.JTextField direccionField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JComboBox<String> mesBox;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField passField;
    private javax.swing.JComboBox<String> restauranteBox;
    private javax.swing.JComboBox<String> tipoIdBox;
    private javax.swing.JComboBox<String> tipoUserBox;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
