/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionrestaurantesFinal;

import Clases.GestionRestaurantes;
import Clases.Empleado;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import org.eclipse.persistence.internal.oxm.mappings.Login;

/**
 *
 * @author Jucaso
 */
public class gestionUsuarios extends javax.swing.JFrame {

    Vector empleados;
   
    
    public gestionUsuarios() {
        super("GESTIONAR USUARIOS");
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
             UIManager.put("OptionPane.background",new ColorUIResource(51,51,51));
             UIManager.put("Panel.background",new ColorUIResource(51,51,51));
             UIManager.put("OptionPane.messageForeground",Color.WHITE);
             UIManager.put("Button.background",Color.BLACK);
             UIManager.put("Button.foreground",Color.WHITE);
       // volver.setIcon(cerrar);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearUsuario = new javax.swing.JButton();
        modUsuario = new javax.swing.JButton();
        idUserHab = new javax.swing.JTextField();
        deshabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTextArea = new javax.swing.JTextArea();
        generarListado = new javax.swing.JButton();
        activar = new javax.swing.JButton();
        diasBox = new javax.swing.JComboBox<>();
        aplicarB = new javax.swing.JButton();
        SalirB = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 445));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        crearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        crearUsuario.setText("Crear usuario");
        crearUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        crearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        crearUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        crearUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, 40));

        modUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modUsuario.setForeground(new java.awt.Color(255, 255, 255));
        modUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        modUsuario.setText("Modificar usuario");
        modUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        modUsuario.setContentAreaFilled(false);
        modUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        modUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        modUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        modUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(modUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 160, 40));

        idUserHab.setBackground(new java.awt.Color(204, 204, 204));
        idUserHab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(idUserHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        deshabilitar.setBackground(new java.awt.Color(255, 255, 255));
        deshabilitar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deshabilitar.setForeground(new java.awt.Color(255, 255, 255));
        deshabilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        deshabilitar.setText("Deshabilitar");
        deshabilitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        deshabilitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deshabilitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deshabilitar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        deshabilitar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        deshabilitar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        deshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(deshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 85, 30));

        usuariosTextArea.setEditable(false);
        usuariosTextArea.setBackground(new java.awt.Color(204, 204, 204));
        usuariosTextArea.setColumns(20);
        usuariosTextArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        usuariosTextArea.setRows(5);
        jScrollPane1.setViewportView(usuariosTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 76, 367, 310));

        generarListado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        generarListado.setForeground(new java.awt.Color(255, 255, 255));
        generarListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        generarListado.setText("Generar listado de usuarios");
        generarListado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        generarListado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generarListado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generarListado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        generarListado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        generarListado.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        generarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarListadoActionPerformed(evt);
            }
        });
        getContentPane().add(generarListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 392, 163, 30));

        activar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        activar.setForeground(new java.awt.Color(255, 255, 255));
        activar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        activar.setText("Activar");
        activar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        activar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        activar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        activar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        activar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        activar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarActionPerformed(evt);
            }
        });
        getContentPane().add(activar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 85, 30));

        diasBox.setBackground(new java.awt.Color(204, 204, 204));
        diasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        diasBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        diasBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diasBox.setFocusable(false);
        getContentPane().add(diasBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 405, 40, 20));

        aplicarB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        aplicarB.setForeground(new java.awt.Color(255, 255, 255));
        aplicarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        aplicarB.setText("Aplicar");
        aplicarB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        aplicarB.setContentAreaFilled(false);
        aplicarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aplicarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aplicarB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        aplicarB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        aplicarB.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        aplicarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarBActionPerformed(evt);
            }
        });
        getContentPane().add(aplicarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 85, 30));

        SalirB.setBackground(new java.awt.Color(153, 153, 153));
        SalirB.setForeground(new java.awt.Color(153, 153, 153));
        SalirB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/cerrar.png"))); // NOI18N
        SalirB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        SalirB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirB.setFocusable(false);
        SalirB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirBMouseExited(evt);
            }
        });
        SalirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBActionPerformed(evt);
            }
        });
        getContentPane().add(SalirB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 30, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/GestionU.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarBActionPerformed

        try {
            File archivo = new File("tiempoCambio.txt");
            FileWriter escribir = new FileWriter(archivo);
            String dias = diasBox.getSelectedItem() + "";
            escribir.write(dias);
            escribir.close();
            
            JOptionPane.showMessageDialog(null, "Se pedirá cambio de contraseña cada " + dias + " días", "AVISO", JOptionPane.PLAIN_MESSAGE, login.CheckIcon);
        } catch (IOException ex) {
            Logger.getLogger(gestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_aplicarBActionPerformed

    private void activarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarActionPerformed
        // Checar si el usuario está activo
        int auxCheck = 0;
        if(!idUserHab.getText().isEmpty() && modificarUsuario.isNumeric(idUserHab.getText())){
            try {
                String auxQuery = "SELECT estado"
                + " FROM empleado"
                + " WHERE id = " + Integer.parseInt(idUserHab.getText()) + ";";
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery(auxQuery);
            } catch (Exception e) {
                System.out.println("Error bro... " + e);
            }

            try {
                while(GestionRestaurantes.rs.next()){
                    if(GestionRestaurantes.rs.getString(1).equals("Activo") ){
                        auxCheck = 1;
                    }
                }
            } catch (Exception e) {
                System.out.println("Error bro... " + e);
            }
            if(auxCheck == 0){
                String auxUpdate = "";
                // Habilitar usuarios
                auxUpdate = "UPDATE empleado"
                + " SET estado = " + "'Activo'" +
                " WHERE id = " + Integer.parseInt(idUserHab.getText()) + ";";
                try {
                    GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                    GestionRestaurantes.s.executeUpdate(auxUpdate);
                } catch (Exception e) {
                    System.out.println("Error en tipo id bro... " + e);
                }
                
                JOptionPane.showMessageDialog(null, "USUARIO ACTIVADO","AVISO", JOptionPane.PLAIN_MESSAGE, login.CheckIcon);
                idUserHab.setText("");
            }
            else{
                
                JOptionPane.showMessageDialog(null, "EL USUARIO YA ESTÁ ACTIVO","ATENCIÓN", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                idUserHab.setText("");
            }

        }
        else{
           
            JOptionPane.showMessageDialog(null, "ID NO VÁLIDO", "ERROR", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
            idUserHab.setText("");
        }
    }//GEN-LAST:event_activarActionPerformed

    private void generarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarListadoActionPerformed
        empleados = new Vector();
        usuariosTextArea.setText("");
        try {
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT id, tipoid, nombre, apellido, email, "
                + " direccion, celular, fechaingreso, usuario, contraseña, tipousuario, idrest FROM empleado;");
            //GestionRestaurantes.s.close();
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }

        try {
            while(GestionRestaurantes.rs.next()){
                Empleado emp;
                emp = new Empleado(GestionRestaurantes.rs.getString(3), GestionRestaurantes.rs.getString(4),
                    Integer.parseInt(GestionRestaurantes.rs.getString(1)), GestionRestaurantes.rs.getString(2), GestionRestaurantes.rs.getString(5),
                    GestionRestaurantes.rs.getString(6), GestionRestaurantes.rs.getLong(7), GestionRestaurantes.rs.getString(8),
                    GestionRestaurantes.rs.getString(9), GestionRestaurantes.rs.getString(10), GestionRestaurantes.rs.getString(11));
                empleados.add(emp);

            }
        } catch (Exception e) {
            System.out.println("Error al mostrar bro... " + e);
           
            JOptionPane.showMessageDialog(null, "OCURRIÓ UN ERROR AL AGREGAR", "ERROR", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
        }
        //System.out.println(empleados.size());
        for(int i=0;i<empleados.size();i++){
            usuariosTextArea.setText(usuariosTextArea.getText()+"\nNombre: "+((Empleado)empleados.elementAt(i)).verEmpNombre()
                + "\nApellido: "+((Empleado)empleados.elementAt(i)).verEmpApellido()
                + "\nID:: "+((Empleado)empleados.elementAt(i)).verEmpId()
                + "\nTipo de ID: "+((Empleado)empleados.elementAt(i)).verEmpTipoId()
                + "\nEmail: "+((Empleado)empleados.elementAt(i)).verEmpEmail()
                + "\nDirección: "+((Empleado)empleados.elementAt(i)).verEmpDireccion()
                + "\nCelular: "+((Empleado)empleados.elementAt(i)).verEmpCelular()
                + "\nFecha de ingreso: "+((Empleado)empleados.elementAt(i)).verEmpFecha()
                + "\nTipo de usuario: "+((Empleado)empleados.elementAt(i)).verEmpTipo()+""
                +"\n______________________________________"
            );
        }
    }//GEN-LAST:event_generarListadoActionPerformed

    private void deshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshabilitarActionPerformed
        // Checar si el usuario está inactivo
        int auxCheck = 0;
        if(!idUserHab.getText().isEmpty() && modificarUsuario.isNumeric(idUserHab.getText())){
            try {
                String auxQuery = "SELECT estado"
                + " FROM empleado"
                + " WHERE id = " + Integer.parseInt(idUserHab.getText()) + ";";
                GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery(auxQuery);
            } catch (Exception e) {
                System.out.println("Error bro... " + e);
            }

            try {
                while(GestionRestaurantes.rs.next()){
                    if(GestionRestaurantes.rs.getString(1).equals("Inactivo")){
                        auxCheck = 1;
                    }
                }
            } catch (Exception e) {
                System.out.println("Error bro... " + e);
            }
            if(auxCheck == 0){
                String auxUpdate = "";
                // Deshabilitar usuarios
                auxUpdate = "UPDATE empleado"
                + " SET estado = " + "'Inactivo'" +
                " WHERE id = " + Integer.parseInt(idUserHab.getText()) + ";";
                try {
                    GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
                    GestionRestaurantes.s.executeUpdate(auxUpdate);
                } catch (Exception e) {
                    System.out.println("Error en tipo id bro... " + e);
                }
                JOptionPane.showMessageDialog(null, "USUARIO DESACTIVADO","AVISO",JOptionPane.PLAIN_MESSAGE, login.CheckIcon);
                idUserHab.setText("");
            }
            else{
                
                JOptionPane.showMessageDialog(null, "EL USUARIO YA ESTÁ INACTIVO", "ATENCIÓN", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                idUserHab.setText("");
            }

        }
        else{
           
            JOptionPane.showMessageDialog(null, "ID NO VÁLIDO", "ERROR", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
            idUserHab.setText("");
        }
    }//GEN-LAST:event_deshabilitarActionPerformed

    private void modUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modUsuarioActionPerformed
        modificarUsuario mu = new modificarUsuario();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modUsuarioActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        CrearUsuario cUsu = new CrearUsuario();
        cUsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void SalirBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirBMouseEntered
        // TODO add your handling code here:
        SalirB.setBackground(new Color (204,204,204));
    }//GEN-LAST:event_SalirBMouseEntered

    private void SalirBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirBMouseExited
        // TODO add your handling code here:
        SalirB.setBackground(new Color (153,153,153));
    }//GEN-LAST:event_SalirBMouseExited

    private void SalirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login log;
        try {
            log = new login();
            log.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(gestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalirBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton SalirB;
    private javax.swing.JButton activar;
    private javax.swing.JButton aplicarB;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JButton deshabilitar;
    private javax.swing.JComboBox<String> diasBox;
    private javax.swing.JButton generarListado;
    private javax.swing.JTextField idUserHab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modUsuario;
    private javax.swing.JTextArea usuariosTextArea;
    // End of variables declaration//GEN-END:variables
}
