/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionrestaurantesFinal;

import Clases.graficoReporte2;
import Clases.tablaReporte1;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Jucaso
 */
public class grafico extends javax.swing.JFrame {

    /**
     * Creates new form grafico
     */
    public grafico() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        if(Reportes.auxGrafico == 1){
            generarGrafico1();
        }
        else if(Reportes.auxGrafico == 2){
            generarGrafico2();
        }
        else if(Reportes.auxGrafico == 3){
            generarGrafico3();
        }
        else if(Reportes.auxGrafico == 4){
            generarGrafico4();
        }
       
    }
    
    public void generarGrafico1(){
        DefaultPieDataset datos = new DefaultPieDataset();
        for (int i = 0; i < Reportes.reporte1.size(); i++) {
            datos.setValue(((tablaReporte1)Reportes.reporte1.elementAt(i)).verNombreProducto(),
                          ((tablaReporte1)Reportes.reporte1.elementAt(i)).verTotal());
        }
        
        JFreeChart grafico = ChartFactory.createPieChart("Gráfico de productos vendidos entre las fechas\n "
                + Reportes.fechaI + " hasta " + Reportes.fechaF , datos, true, true, false);
        
        ChartPanel panel = new ChartPanel(grafico);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,400));
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel, BorderLayout.NORTH);
        
        pack();
        repaint();
    }
    
    public void generarGrafico2(){
        DefaultPieDataset datos = new DefaultPieDataset();
        for (int i = 0; i < Reportes.reporte2.size(); i++) {
            datos.setValue(((graficoReporte2)Reportes.reporte2.elementAt(i)).verDia(),
                          ((graficoReporte2)Reportes.reporte2.elementAt(i)).verTotalVentas());
        }
        
        JFreeChart grafico = ChartFactory.createPieChart("Gráfico de productos vendidos entre las fechas\n "
                + Reportes.fechaI + " hasta " + Reportes.fechaF  + " por dia de la semana.", datos, true, true, false);
        
        ChartPanel panel = new ChartPanel(grafico);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,400));
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel, BorderLayout.NORTH);
        
        pack();
        repaint();
    }
    
    public void generarGrafico3(){
        DefaultPieDataset datos = new DefaultPieDataset();
        for (int i = 0; i < Reportes.reporte3.size(); i++) {
            datos.setValue(((graficoReporte2)Reportes.reporte3.elementAt(i)).verDia(),
                          ((graficoReporte2)Reportes.reporte3.elementAt(i)).verTotalVentas());
        }
        
        JFreeChart grafico = ChartFactory.createPieChart("Gráfico de insumos registrados entre las fechas\n "
                + Reportes.fechaI + " hasta " + Reportes.fechaF  + " por dia de la semana.", datos, true, true, false);
        
        ChartPanel panel = new ChartPanel(grafico);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,400));
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel, BorderLayout.NORTH);
        
        pack();
        repaint();
    }
    
    public void generarGrafico4(){
        DefaultPieDataset datos = new DefaultPieDataset();
        for (int i = 0; i < Reportes.reporte4.size(); i++) {
            datos.setValue(((graficoReporte2)Reportes.reporte4.elementAt(i)).verDia(),
                          ((graficoReporte2)Reportes.reporte4.elementAt(i)).verTotalVentas());
        }
        
        JFreeChart grafico = ChartFactory.createPieChart("Gráfico de ventas promedio por restaurante", datos, true, true, false);
        
        ChartPanel panel = new ChartPanel(grafico);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,400));
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel, BorderLayout.NORTH);
        
        pack();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
