/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionrestaurantesFinal;

import Clases.GestionRestaurantes;
import static gestionrestaurantesFinal.CrearUsuario.isNumeric;
import javax.swing.JOptionPane;

/**
 *
 * @author Jucaso
 */
public class regPnoPreparado extends javax.swing.JFrame {

    int newIDins = 0, newIDproducto = 0,newIDrequiere, acc = 1;
    public regPnoPreparado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setCodigoIns();
        setCodigoProducto();
        setCodigoRequiere();
        //acc++;
    }
    public void setCodigoIns(){
        try {
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT * FROM insumos order by id;"); 
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }

        try {
            while(GestionRestaurantes.rs.next()){
                System.out.println(GestionRestaurantes.rs.getInt(1));
                newIDins= GestionRestaurantes.rs.getInt(1) + acc;
            }
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }        
    }
    
    public void setCodigoProducto(){
        try {
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT * FROM producto order by id ;"); 
        } catch (Exception e) {
        }

        try {
            while(GestionRestaurantes.rs.next()){
                newIDproducto = GestionRestaurantes.rs.getInt(1) + acc;
            }
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }       
    }
    
    public void setCodigoRequiere(){
        try {
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.rs = GestionRestaurantes.s.executeQuery("SELECT * FROM requiere order by codigo ;"); 
        } catch (Exception e) {
        }

        try {
            while(GestionRestaurantes.rs.next()){
                newIDrequiere = GestionRestaurantes.rs.getInt(1) + acc;
            }
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        nombreP = new javax.swing.JTextField();
        cantP = new javax.swing.JTextField();
        registrarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        valorVenta = new javax.swing.JTextField();
        costoAdq = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 404, 10));
        getContentPane().add(nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 38, 110, -1));
        getContentPane().add(cantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 92, 111, -1));

        registrarB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registrarB.setForeground(new java.awt.Color(255, 255, 255));
        registrarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotones.jpg"))); // NOI18N
        registrarB.setText("Registrar");
        registrarB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        registrarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrarB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressedP.jpg"))); // NOI18N
        registrarB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        registrarB.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoBotonesPressed.jpg"))); // NOI18N
        registrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBActionPerformed(evt);
            }
        });
        getContentPane().add(registrarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 40));

        cancelarB.setText("Volver");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        getContentPane().add(valorVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 66, 110, -1));
        getContentPane().add(costoAdq, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 120, 111, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/RegistrarPnP.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 433, 167));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBActionPerformed
        int check = 0;
        String nombre = "";
        String cantidad = "";
        int valor = 0;
        int costoAdquisicion = 0;
        
        if(!nombreP.getText().isEmpty() && !isNumeric(nombreP.getText())){
            nombre = nombreP.getText();
            if(!cantP.getText().isEmpty() && isNumeric(cantP.getText())){
                cantidad = cantP.getText();
                if(!valorVenta.getText().isEmpty() && isNumeric(valorVenta.getText())){
                    valor = Integer.parseInt(valorVenta.getText());
                    if(!costoAdq.getText().isEmpty() && isNumeric(costoAdq.getText())){
                        costoAdquisicion = Integer.parseInt(costoAdq.getText());
                        check = 1;
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "COSTO DE ADQUISICIÓN NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "VALOR DE VENTA NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "CANTIDAD NO VÁLIDA", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "NOMBRE NO VÁLIDO", "ADVERTENCIA", JOptionPane.PLAIN_MESSAGE, login.WrongIcon);
        }
        
        
        
        
        if(check == 1){
           try {
            String auxUpdate = "INSERT INTO producto values(" + newIDproducto +
                    "," + "'" + nombre + "'" + "," + valor + "," + login.auxIdRes + "," + "'No preparado'" + ");";
            
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.s.executeUpdate(auxUpdate);
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }
        
        try {
            String auxUpdate = "INSERT INTO insumos values(" + newIDins +
                    "," + "'" + nombre + "'" + "," + costoAdquisicion + "," + cantidad + "," + login.auxIdRes + ");";
            
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.s.executeUpdate(auxUpdate);
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }
        
        try {
            String auxUpdate = "INSERT INTO requiere values(" + newIDrequiere +
                    "," + newIDproducto + "," + newIDins + "," + 1 + "," + login.auxIdRes + ");";
            
            GestionRestaurantes.s  = GestionRestaurantes.conn.createStatement();
            GestionRestaurantes.s.executeUpdate(auxUpdate);
        } catch (Exception e) {
            System.out.println("Error bro... " + e);
        }
        
        nombreP.setText("");
        cantP.setText("");
        valorVenta.setText("");
        costoAdq.setText("");
        acc++;
        JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO", "AVISO", JOptionPane.PLAIN_MESSAGE, login.CheckIcon); 
        }
        
        
        
    }//GEN-LAST:event_registrarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        this.dispose();
        AdmonRes a1 = new AdmonRes();
        a1.setVisible(true);
    }//GEN-LAST:event_cancelarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regPnoPreparado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regPnoPreparado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regPnoPreparado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regPnoPreparado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regPnoPreparado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarB;
    private javax.swing.JTextField cantP;
    private javax.swing.JTextField costoAdq;
    private javax.swing.JLabel fondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreP;
    private javax.swing.JButton registrarB;
    private javax.swing.JTextField valorVenta;
    // End of variables declaration//GEN-END:variables
}
